In [152]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler,LabelEncoder,OrdinalEncoder
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [153]:
data=pd.read_csv(r"C:\Users\GOPESHWAR KUMAR\Document\JupyterNoteBook\Dataset\loan_approval_dataset.csv")

In [154]:
data.head(2)

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected

In [155]:
data.tail(2)

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
4267,4268,1,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4268,4269,1,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

In [156]:
data.shape,data.size

((4269, 13), 55497)

In [157]:
data.isnull().sum()

loan_id                      0
 no_of_dependents            0
 education                   0
 self_employed               0
 income_annum                0
 loan_amount                 0
 loan_term                   0
 cibil_score                 0
 residential_assets_value    0
 commercial_assets_value     0
 luxury_assets_value         0
 bank_asset_value            0
 loan_status                 0
dtype: int64

In [158]:
data.drop("loan_id",inplace=True,axis=1)

In [159]:
ordinal=OrdinalEncoder()
label=LabelEncoder()

In [187]:
x=data.iloc[: ,:-1]
y=data.iloc[:,11]

In [194]:
x=ordinal.fit_transform(x)

In [168]:
y=label.fit_transform(y)

In [169]:
scale=StandardScaler()

In [170]:
x=scale.fit_transform(x)

In [196]:
x_train,y_train,x_test,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [172]:
model=GaussianNB()

In [ ]:
model.fit(x_train,y_train)

In [197]:
model.predict(x_test)

NotFittedError: This GaussianNB instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
model.score(x_test,y_test)*100

In [198]:
model.score(x_train,y_train)*100

NotFittedError: This GaussianNB instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.